### ISSUE TITLE
Compiling issue "uint128_t uint128_t"

### ISSUE THREAD

**Issue by cazxtc** [iabem97/houdini-public#47]
<img width="1023" alt="bildschirmfoto 2018-06-09 um 13 20 02" src="https://user-images.githubusercontent.com/34897759/41191037-70d11e60-6be9-11e8-95df-b8866655ef15.png">

can anyone tell me what that mistake is

**Comment by TravisBrown01** [comment]
It would help if you can have a screen shot of the full screen

**Comment by cazxtc** [comment]
<img width="1280" alt="bildschirmfoto 2018-06-09 um 15 41 15" src="https://user-images.githubusercontent.com/34897759/41192311-10b366b0-6bfc-11e8-9443-66e17bf16d75.png">

**Comment by SeaJae** [comment]
Connect your iPhone to your mac via usb. From the top where it says “generic iOS device” select your phone by name.

**Comment by cazxtc** [comment]
I have already done that....
it just was not connected at the screenshot

**Comment by ipatch** [comment]
@cazxtc I got the same `error` / `warning` when trying to build the `.ipa` from Xcode as well.

Use the provided `compile.sh` script to compile Xcode project, and you shouldn't have any issues.  However, if you don't have a developer account, then houdini won't be able to jailbreak your device, due to the fact that your developer profile / account is missing the **multipath** capability provided by the paid developer account.

![compile](https://i.imgur.com/0Mmt7A1.png)

![fail](https://i.imgur.com/mjJhKpl.png)
